- group: Bonus
  start: 30-09-2023 14:00
  deadline: 18-02-2024 23:59
  tasks:
    - task: consistenthash
      score: 200
    - task: gossip
      score: 300
    - task: smartsched
      score: 200
      watch:
        - distbuild/pkg/scheduler
    - task: wasm
      score: 300

- group: Analysis
  start: 30-09-2023 14:00
  deadline: 11-02-2023 23:59
  tasks:
    - task: testifycheck
      score: 200
    - task: gzep
      score: 100

- group: "[HW] Dist Build"
  start: 30-09-2023 14:00
  deadline: 04-02-2024 23:59
  tasks:
    - task: distbuild
      score: 0

- group: Low level
  start: 30-09-2023 14:00
  deadline: 28-01-2024 23:59
  tasks:
    - task: illegal
      score: 100
    - task: blowfish
      score: 100

- group: Reflect
  start: 30-09-2023 14:00
  deadline: 21-01-2024 23:59
  tasks:
    - task: reversemap
      score: 100
    - task: jsonlist
      score: 100
    - task: jsonrpc
      score: 100
    - task: structtags
      score: 100

- group: SQL
  start: 30-09-2023 14:00
  deadline: 31-12-2023 23:59
  tasks:
    - task: dao
      score: 100
    - task: ledger
      score: 200
    - task: shopfront
      score: 100
    - task: wscat
      score: 200

- group: Generics
  start: 30-09-2023 14:00
  deadline: 24-12-2023 23:59
  tasks:
    - task: genericsum
      score: 100
    - task: treeiter
      score: 100
    - task: coverme
      score: 300

- group: HTTP
  start: 30-09-2023 14:00
  deadline: 17-12-2023 23:59
  tasks:
    - task: urlshortener
      score: 100
    - task: digitalclock
      score: 100
    - task: middleware
      score: 200
    - task: olympics
      score: 200
    - task: firewall
      score: 200

- group: Concurrency with shared memory
  start: 30-09-2023 14:00
  deadline: 03-12-2023 23:59
  tasks:
    - task: dupcall
      score: 200
    - task: keylock
      score: 200
    - task: batcher
      score: 200
    - task: pubsub
      score: 300

- group: Testing
  start: 30-09-2023 14:00
  deadline: 26-11-2023 23:59
  tasks:
    - task: testequal
      score: 100
    - task: fileleak
      score: 100
    - task: tabletest
      score: 100
    - task: tparallel
      score: 200
    - task: iprange
      score: 100

- group: "[HW] Gitfame"
  start: 30-09-2023 14:00
  deadline: 19-11-2023 23:59
  tasks:
    - task: gitfame
      score: 0

- group: Goroutines
  start: 30-09-2023 14:00
  deadline: 05-11-2023 23:59
  tasks:
    - task: tour1
      score: 100
    - task: once
      score: 100
    - task: rwmutex
      score: 100
    - task: waitgroup
      score: 100
    - task: cond
      score: 100
    - task: ratelimit
      score: 100

- group: Interfaces
  start: 30-09-2023 14:00
  deadline: 29-10-2023 23:59
  tasks:
    - task: otp
      score: 100
    - task: lrucache
      score: 100
    - task: externalsort
      score: 100
    - task: retryupdate
      score: 100
    - task: ciletters
      score: 100

- group: Basics
  start: 30-09-2023 14:00
  deadline: 22-10-2023 23:59
  tasks:
    - task: hotelbusiness
      score: 100
    - task: hogwarts
      score: 100
    - task: utf8
      score: 100
    - task: varfmt
      score: 100
    - task: speller
      score: 100
    - task: forth
      score: 100

- group: Hello World
  start: 30-09-2023 14:00
  deadline: 15-10-2023 23:59
  tasks:
    - task: sum
      score: 100
    - task: tour0
      score: 100
    - task: wordcount
      score: 100
    - task: urlfetch
      score: 100
    - task: fetchall
      score: 100
